name: .NET Console App - Build and Format Check

on:
  push:
    branches:
      - '**'

jobs:
  build-and-format:
    runs-on: windows-latest  # Windows runner is better for VS solutions

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Or match your version (e.g., 7.0.x or 6.0.x)

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Check code formatting
        run: dotnet format --verify-no-changes --severity info

      # Optional: Add test step if you use unit tests
      # - name: Run tests
      #   run: dotnet test --no-build --verbosity normal
