name: .NET Console App - Build and Format Check

on:
  push:
    branches:
      - '**'

jobs:
  build-and-format:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Match your actual .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Check code formatting
        run: dotnet format --verify-no-changes
